#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
"""Garmin Connect sync script for GarminCoach HA Addon.

Pulls latest health data from Garmin Connect API and inserts into the
local PostgreSQL database. Runs periodically via the s6 service manager.

Supports two auth modes:
  1. Saved tokens in /data/garmin-tokens/ (preferred, from generate-garmin-tokens.py)
  2. Email/password from environment variables (fallback)
"""

import json
import os
import sys
from datetime import datetime, timedelta, timezone

try:
    from garminconnect import Garmin
except ImportError:
    print("ERROR: garminconnect not installed", file=sys.stderr)
    sys.exit(1)

try:
    import psycopg2
except ImportError:
    print("ERROR: psycopg2 not installed", file=sys.stderr)
    sys.exit(1)


DATABASE_URL = os.environ.get("DATABASE_URL", "postgresql://postgres@127.0.0.1:5432/garmincoach")
GARMIN_EMAIL = os.environ.get("GARMIN_EMAIL", "")
GARMIN_PASSWORD = os.environ.get("GARMIN_PASSWORD", "")
TOKEN_DIR = "/data/garmin-tokens"


def get_client():
    """Authenticate with Garmin Connect, preferring saved tokens."""
    os.makedirs(TOKEN_DIR, exist_ok=True)
    oauth1_path = os.path.join(TOKEN_DIR, "oauth1_token.json")
    oauth2_path = os.path.join(TOKEN_DIR, "oauth2_token.json")

    # Mode 1: Resume from saved garth tokens (generated by generate-garmin-tokens.py)
    if os.path.exists(oauth1_path) and os.path.exists(oauth2_path):
        try:
            client = Garmin(GARMIN_EMAIL or "token-user")
            client.login(tokenstore=TOKEN_DIR)
            # Re-save tokens (refreshes OAuth2 if needed)
            client.garth.dump(TOKEN_DIR)
            print("Authenticated with saved tokens")
            return client
        except Exception as e:
            print(f"Saved tokens failed: {e}", file=sys.stderr)
            print("Try re-running scripts/generate-garmin-tokens.py", file=sys.stderr)

    # Mode 2: Email/password login
    if GARMIN_EMAIL and GARMIN_PASSWORD:
        try:
            client = Garmin(GARMIN_EMAIL, GARMIN_PASSWORD)
            client.login()
            client.garth.dump(TOKEN_DIR)
            print("Authenticated with credentials, tokens saved")
            return client
        except Exception as e:
            print(f"Credential login failed: {e}", file=sys.stderr)

    return None


def get_db():
    """Connect to PostgreSQL."""
    return psycopg2.connect(DATABASE_URL)


def sync_daily_stats(client, db, date_str):
    """Sync daily health stats for a given date."""
    cur = db.cursor()
    try:
        stats = client.get_stats(date_str)
        sleep_data = client.get_sleep_data(date_str)
        hrv = client.get_hrv_data(date_str)
        stress = client.get_stress_data(date_str)

        sleep_dto = sleep_data.get("dailySleepDTO", {}) if sleep_data else {}

        cur.execute("""
            INSERT INTO daily_metric (
                user_id, date, steps, calories, resting_hr, max_hr,
                total_sleep_minutes, deep_sleep_minutes, rem_sleep_minutes,
                light_sleep_minutes, awake_minutes, sleep_score,
                hrv, stress_score, body_battery_start, body_battery_end,
                floors_climbed, intensity_minutes, synced_at
            ) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
            ON CONFLICT (user_id, date) DO UPDATE SET
                steps = EXCLUDED.steps,
                calories = EXCLUDED.calories,
                resting_hr = EXCLUDED.resting_hr,
                max_hr = EXCLUDED.max_hr,
                total_sleep_minutes = EXCLUDED.total_sleep_minutes,
                deep_sleep_minutes = EXCLUDED.deep_sleep_minutes,
                rem_sleep_minutes = EXCLUDED.rem_sleep_minutes,
                light_sleep_minutes = EXCLUDED.light_sleep_minutes,
                awake_minutes = EXCLUDED.awake_minutes,
                sleep_score = EXCLUDED.sleep_score,
                hrv = EXCLUDED.hrv,
                stress_score = EXCLUDED.stress_score,
                body_battery_start = EXCLUDED.body_battery_start,
                body_battery_end = EXCLUDED.body_battery_end,
                floors_climbed = EXCLUDED.floors_climbed,
                intensity_minutes = EXCLUDED.intensity_minutes,
                synced_at = EXCLUDED.synced_at
        """, (
            "addon-user",
            date_str,
            stats.get("totalSteps"),
            stats.get("totalKilocalories"),
            stats.get("restingHeartRate"),
            stats.get("maxHeartRate"),
            sleep_dto.get("sleepTimeSeconds", 0) // 60 if sleep_dto else None,
            sleep_dto.get("deepSleepSeconds", 0) // 60 if sleep_dto else None,
            sleep_dto.get("remSleepSeconds", 0) // 60 if sleep_dto else None,
            sleep_dto.get("lightSleepSeconds", 0) // 60 if sleep_dto else None,
            sleep_dto.get("awakeSleepSeconds", 0) // 60 if sleep_dto else None,
            sleep_dto.get("sleepScores", {}).get("overall", {}).get("value"),
            hrv.get("hrvSummary", {}).get("weeklyAvg") if hrv else None,
            stress.get("averageStressLevel") if stress else None,
            stats.get("bodyBatteryChargedValue"),
            stats.get("bodyBatteryDrainedValue"),
            stats.get("floorsAscended"),
            stats.get("intensityMinutesGoal"),
            datetime.now(timezone.utc).isoformat(),
        ))
        db.commit()
        print(f"  Synced daily stats for {date_str}")
    except Exception as e:
        db.rollback()
        print(f"  Failed to sync {date_str}: {e}", file=sys.stderr)
    finally:
        cur.close()


def sync_activities(client, db, days=7):
    """Sync recent activities."""
    cur = db.cursor()
    try:
        activities = client.get_activities(0, days * 3)
        for act in activities:
            act_id = str(act.get("activityId", ""))
            cur.execute("""
                INSERT INTO activity (
                    user_id, garmin_activity_id, sport_type, sub_type,
                    started_at, duration_minutes, distance_meters,
                    avg_hr, max_hr, calories, avg_pace_sec_per_km,
                    aerobic_te, anaerobic_te, synced_at, raw_garmin_data
                ) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
                ON CONFLICT (garmin_activity_id) DO UPDATE SET
                    synced_at = EXCLUDED.synced_at,
                    raw_garmin_data = EXCLUDED.raw_garmin_data
            """, (
                "addon-user",
                act_id,
                act.get("activityType", {}).get("typeKey", "other"),
                act.get("activityType", {}).get("typeId", ""),
                act.get("startTimeLocal"),
                (act.get("duration", 0) or 0) / 60,
                act.get("distance"),
                act.get("averageHR"),
                act.get("maxHR"),
                act.get("calories"),
                act.get("averageSpeed"),
                act.get("aerobicTrainingEffect"),
                act.get("anaerobicTrainingEffect"),
                datetime.now(timezone.utc).isoformat(),
                json.dumps(act),
            ))
        db.commit()
        print(f"  Synced {len(activities)} activities")
    except Exception as e:
        db.rollback()
        print(f"  Failed to sync activities: {e}", file=sys.stderr)
    finally:
        cur.close()


def main():
    has_tokens = (
        os.path.exists(os.path.join(TOKEN_DIR, "oauth1_token.json"))
        and os.path.exists(os.path.join(TOKEN_DIR, "oauth2_token.json"))
    )

    if not has_tokens and (not GARMIN_EMAIL or not GARMIN_PASSWORD):
        print("No Garmin tokens or credentials configured, skipping sync")
        return

    print(f"Starting Garmin sync at {datetime.now(timezone.utc).isoformat()}")
    client = get_client()
    if client is None:
        print("Failed to authenticate with Garmin, skipping sync", file=sys.stderr)
        return

    db = get_db()

    today = datetime.now(timezone.utc).date()
    for days_ago in range(7):
        date_str = (today - timedelta(days=days_ago)).isoformat()
        sync_daily_stats(client, db, date_str)

    sync_activities(client, db, days=7)

    db.close()
    print("Garmin sync complete")


if __name__ == "__main__":
    main()
