#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
"""Garmin Connect sync script for GarminCoach HA Addon.

Pulls latest health data from Garmin Connect API and inserts into the
local PostgreSQL database. Runs periodically via the s6 service manager.

Supports two auth modes:
  1. Saved tokens in /data/garmin-tokens/ (preferred, from generate-garmin-tokens.py)
  2. Email/password from environment variables (fallback)
"""

import json
import os
import sys
from datetime import datetime, timedelta, timezone

try:
    from garminconnect import Garmin
except ImportError:
    print("ERROR: garminconnect not installed", file=sys.stderr)
    sys.exit(1)

try:
    import psycopg2
except ImportError:
    print("ERROR: psycopg2 not installed", file=sys.stderr)
    sys.exit(1)


DATABASE_URL = os.environ.get("DATABASE_URL", "postgresql://postgres@127.0.0.1:5432/garmincoach")
GARMIN_EMAIL = os.environ.get("GARMIN_EMAIL", "")
GARMIN_PASSWORD = os.environ.get("GARMIN_PASSWORD", "")
TOKEN_DIR = "/data/garmin-tokens"
# Must match the userId used by the Next.js app (DEV_BYPASS_AUTH seed user)
USER_ID = os.environ.get("GARMIN_USER_ID", "seed-user-001")

SYNC_STATUS_FILE = os.path.join(TOKEN_DIR, ".sync_status")


def _write_sync_status(phase, detail="", progress=0):
    """Write sync progress to a shared status file for the auth server."""
    import json as _json
    os.makedirs(TOKEN_DIR, exist_ok=True)
    status = {
        "syncing": True,
        "phase": phase,
        "detail": detail,
        "progress": progress,
        "updated_at": datetime.now(timezone.utc).isoformat(),
    }
    try:
        with open(SYNC_STATUS_FILE, "w") as f:
            _json.dump(status, f)
    except Exception:
        pass


def _clear_sync_status():
    """Clear sync status file when sync completes."""
    import json as _json
    status = {
        "syncing": False,
        "phase": "idle",
        "detail": "",
        "progress": 100,
        "updated_at": datetime.now(timezone.utc).isoformat(),
    }
    try:
        with open(SYNC_STATUS_FILE, "w") as f:
            _json.dump(status, f)
    except Exception:
        pass


def get_client():
    """Authenticate with Garmin Connect, preferring saved tokens."""
    os.makedirs(TOKEN_DIR, exist_ok=True)
    oauth1_path = os.path.join(TOKEN_DIR, "oauth1_token.json")
    oauth2_path = os.path.join(TOKEN_DIR, "oauth2_token.json")

    # Mode 1: Resume from saved garth tokens (generated by generate-garmin-tokens.py)
    if os.path.exists(oauth1_path) and os.path.exists(oauth2_path):
        try:
            client = Garmin(GARMIN_EMAIL or "token-user")
            client.login(tokenstore=TOKEN_DIR)
            # Re-save tokens (refreshes OAuth2 if needed)
            client.garth.dump(TOKEN_DIR)
            print("Authenticated with saved tokens")
            return client
        except Exception as e:
            print(f"Saved tokens failed: {e}", file=sys.stderr)
            print("Try re-running scripts/generate-garmin-tokens.py", file=sys.stderr)

    # Mode 2: Email/password login
    if GARMIN_EMAIL and GARMIN_PASSWORD:
        try:
            client = Garmin(GARMIN_EMAIL, GARMIN_PASSWORD)
            client.login()
            client.garth.dump(TOKEN_DIR)
            print("Authenticated with credentials, tokens saved")
            return client
        except Exception as e:
            print(f"Credential login failed: {e}", file=sys.stderr)

    return None


def get_db():
    """Connect to PostgreSQL."""
    return psycopg2.connect(DATABASE_URL)


def _safe_sleep_minutes(sleep_dto, key):
    """Safely extract sleep seconds and convert to minutes."""
    val = sleep_dto.get(key)
    if val is None:
        return None
    return val // 60


def sync_daily_stats(client, db, date_str):
    """Sync daily health stats for a given date."""
    cur = db.cursor()
    try:
        stats = client.get_stats(date_str)
        sleep_data = client.get_sleep_data(date_str)
        hrv = client.get_hrv_data(date_str)
        stress = client.get_stress_data(date_str)

        sleep_dto = sleep_data.get("dailySleepDTO", {}) if sleep_data else {}

        # Ensure unique constraint exists for upsert
        cur.execute("""
            DO $$ BEGIN
                IF NOT EXISTS (
                    SELECT 1 FROM pg_constraint
                    WHERE conname = 'daily_metric_user_date_uq'
                ) THEN
                    ALTER TABLE daily_metric
                        ADD CONSTRAINT daily_metric_user_date_uq
                        UNIQUE (user_id, date);
                END IF;
            END $$;
        """)

        cur.execute("""
            INSERT INTO daily_metric (
                user_id, date, steps, calories, resting_hr, max_hr,
                total_sleep_minutes, deep_sleep_minutes, rem_sleep_minutes,
                light_sleep_minutes, awake_minutes, sleep_score,
                hrv, stress_score, body_battery_start, body_battery_end,
                floors_climbed, intensity_minutes, synced_at
            ) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
            ON CONFLICT (user_id, date) DO UPDATE SET
                steps = EXCLUDED.steps,
                calories = EXCLUDED.calories,
                resting_hr = EXCLUDED.resting_hr,
                max_hr = EXCLUDED.max_hr,
                total_sleep_minutes = EXCLUDED.total_sleep_minutes,
                deep_sleep_minutes = EXCLUDED.deep_sleep_minutes,
                rem_sleep_minutes = EXCLUDED.rem_sleep_minutes,
                light_sleep_minutes = EXCLUDED.light_sleep_minutes,
                awake_minutes = EXCLUDED.awake_minutes,
                sleep_score = EXCLUDED.sleep_score,
                hrv = EXCLUDED.hrv,
                stress_score = EXCLUDED.stress_score,
                body_battery_start = EXCLUDED.body_battery_start,
                body_battery_end = EXCLUDED.body_battery_end,
                floors_climbed = EXCLUDED.floors_climbed,
                intensity_minutes = EXCLUDED.intensity_minutes,
                synced_at = EXCLUDED.synced_at
        """, (
            USER_ID,
            date_str,
            stats.get("totalSteps"),
            stats.get("totalKilocalories"),
            stats.get("restingHeartRate"),
            stats.get("maxHeartRate"),
            _safe_sleep_minutes(sleep_dto, "sleepTimeSeconds"),
            _safe_sleep_minutes(sleep_dto, "deepSleepSeconds"),
            _safe_sleep_minutes(sleep_dto, "remSleepSeconds"),
            _safe_sleep_minutes(sleep_dto, "lightSleepSeconds"),
            _safe_sleep_minutes(sleep_dto, "awakeSleepSeconds"),
            sleep_dto.get("sleepScores", {}).get("overall", {}).get("value"),
            hrv.get("hrvSummary", {}).get("weeklyAvg") if hrv else None,
            stress.get("averageStressLevel") if stress else None,
            stats.get("bodyBatteryChargedValue"),
            stats.get("bodyBatteryDrainedValue"),
            stats.get("floorsAscended"),
            stats.get("intensityMinutesGoal"),
            datetime.now(timezone.utc).isoformat(),
        ))
        db.commit()
        print(f"  Synced daily stats for {date_str}")
    except Exception as e:
        db.rollback()
        print(f"  Failed to sync {date_str}: {e}", file=sys.stderr)
    finally:
        cur.close()


def sync_activities(client, db, days=7):
    """Sync activities, fetching in batches of 100."""
    cur = db.cursor()
    try:
        # Ensure unique constraint exists for upsert
        cur.execute("""
            DO $$ BEGIN
                IF NOT EXISTS (
                    SELECT 1 FROM pg_constraint
                    WHERE conname = 'activity_garmin_id_uq'
                ) THEN
                    ALTER TABLE activity
                        ADD CONSTRAINT activity_garmin_id_uq
                        UNIQUE (garmin_activity_id);
                END IF;
            END $$;
        """)

        total = 0
        batch_size = 100
        start = 0
        while True:
            activities = client.get_activities(start, batch_size)
            if not activities:
                break

            for act in activities:
                act_id = str(act.get("activityId", ""))
                # Extract HR zone minutes (seconds → minutes)
                hr_zones = None
                z1 = act.get("hrTimeInZone_1")
                if z1 is not None:
                    hr_zones = json.dumps({
                        "zone1": round((act.get("hrTimeInZone_1", 0) or 0) / 60, 1),
                        "zone2": round((act.get("hrTimeInZone_2", 0) or 0) / 60, 1),
                        "zone3": round((act.get("hrTimeInZone_3", 0) or 0) / 60, 1),
                        "zone4": round((act.get("hrTimeInZone_4", 0) or 0) / 60, 1),
                        "zone5": round((act.get("hrTimeInZone_5", 0) or 0) / 60, 1),
                    })

                # Compute TRIMP from avg HR and duration
                avg_hr = act.get("averageHR")
                duration_min = (act.get("duration", 0) or 0) / 60
                trimp = None
                if avg_hr and duration_min > 0:
                    # Simplified TRIMP: duration * intensity factor
                    hr_ratio = avg_hr / 200.0  # Normalized intensity
                    trimp = round(duration_min * hr_ratio * 0.64 * (1.92 ** hr_ratio), 1)

                cur.execute("""
                    INSERT INTO activity (
                        user_id, garmin_activity_id, sport_type, sub_type,
                        started_at, duration_minutes, distance_meters,
                        avg_hr, max_hr, calories, avg_pace_sec_per_km,
                        aerobic_te, anaerobic_te, hr_zone_minutes,
                        trimp_score, strain_score, synced_at, raw_garmin_data
                    ) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
                    ON CONFLICT (garmin_activity_id) DO UPDATE SET
                        hr_zone_minutes = COALESCE(EXCLUDED.hr_zone_minutes, activity.hr_zone_minutes),
                        trimp_score = COALESCE(EXCLUDED.trimp_score, activity.trimp_score),
                        strain_score = COALESCE(EXCLUDED.strain_score, activity.strain_score),
                        synced_at = EXCLUDED.synced_at,
                        raw_garmin_data = EXCLUDED.raw_garmin_data
                """, (
                    USER_ID,
                    act_id,
                    act.get("activityType", {}).get("typeKey", "other"),
                    act.get("activityType", {}).get("typeId", ""),
                    act.get("startTimeLocal"),
                    duration_min,
                    act.get("distance"),
                    avg_hr,
                    act.get("maxHR"),
                    act.get("calories"),
                    act.get("averageSpeed"),
                    act.get("aerobicTrainingEffect"),
                    act.get("anaerobicTrainingEffect"),
                    hr_zones,
                    trimp,
                    act.get("activityTrainingLoad"),
                    datetime.now(timezone.utc).isoformat(),
                    json.dumps(act),
                ))
            db.commit()
            total += len(activities)
            print(f"  Synced batch: {len(activities)} activities (total: {total})")

            if len(activities) < batch_size:
                break
            start += batch_size

            # Incremental syncs: stop after enough recent activities
            if days <= 30 and total >= 50:
                break

        print(f"  Synced {total} activities total")
    except Exception as e:
        db.rollback()
        print(f"  Failed to sync activities: {e}", file=sys.stderr)
    finally:
        cur.close()


def backfill_from_raw_json(db):
    """Extract hr_zone_minutes, strain_score, trimp_score from stored raw_garmin_data."""
    cur = db.cursor()
    try:
        cur.execute("""
            SELECT id, raw_garmin_data, avg_hr, duration_minutes
            FROM activity
            WHERE user_id = %s
              AND raw_garmin_data IS NOT NULL
              AND (hr_zone_minutes IS NULL OR strain_score IS NULL)
        """, (USER_ID,))
        rows = cur.fetchall()
        if not rows:
            return

        updated = 0
        for row_id, raw_json, avg_hr, duration_min in rows:
            act = json.loads(raw_json) if isinstance(raw_json, str) else raw_json

            # Extract HR zones (seconds → minutes)
            hr_zones = None
            z1 = act.get("hrTimeInZone_1")
            if z1 is not None:
                hr_zones = json.dumps({
                    "zone1": round((act.get("hrTimeInZone_1", 0) or 0) / 60, 1),
                    "zone2": round((act.get("hrTimeInZone_2", 0) or 0) / 60, 1),
                    "zone3": round((act.get("hrTimeInZone_3", 0) or 0) / 60, 1),
                    "zone4": round((act.get("hrTimeInZone_4", 0) or 0) / 60, 1),
                    "zone5": round((act.get("hrTimeInZone_5", 0) or 0) / 60, 1),
                })

            # Garmin training load
            strain = act.get("activityTrainingLoad")

            # Compute TRIMP if we have HR data
            trimp = None
            if avg_hr and duration_min and duration_min > 0:
                hr_ratio = avg_hr / 200.0
                trimp = round(duration_min * hr_ratio * 0.64 * (1.92 ** hr_ratio), 1)

            if hr_zones or strain or trimp:
                cur.execute("""
                    UPDATE activity SET
                        hr_zone_minutes = COALESCE(%s, hr_zone_minutes),
                        strain_score = COALESCE(%s, strain_score),
                        trimp_score = COALESCE(%s, trimp_score)
                    WHERE id = %s
                """, (hr_zones, strain, trimp, row_id))
                updated += 1

        db.commit()
        if updated:
            print(f"  Backfilled {updated} activities with zones/strain/TRIMP")
    except Exception as e:
        db.rollback()
        print(f"  Backfill failed: {e}", file=sys.stderr)
    finally:
        cur.close()


def sync_vo2max(client, db, days=7):
    """Compute and upsert VO2max estimates from running activities and daily stats."""
    cur = db.cursor()
    try:
        # Ensure unique constraint exists for upsert
        cur.execute("""
            DO $$ BEGIN
                IF NOT EXISTS (
                    SELECT 1 FROM pg_constraint
                    WHERE conname = 'vo2max_estimate_user_date_sport_uq'
                ) THEN
                    ALTER TABLE vo2max_estimate
                        ADD CONSTRAINT vo2max_estimate_user_date_sport_uq
                        UNIQUE (user_id, date, sport);
                END IF;
            END $$;
        """)

        # Delete old (incorrect) VO2max records so they get recalculated
        cur.execute("DELETE FROM vo2max_estimate WHERE user_id = %s AND source IN ('running_pace_hr', 'uth_method')", (USER_ID,))

        # Fetch user age for age-predicted max HR
        cur.execute("SELECT age FROM profile WHERE user_id = %s", (USER_ID,))
        age_row = cur.fetchone()
        if not age_row or not age_row[0]:
            print("  No age in profile — skipping VO2max (needed for HRmax estimation)")
            return
        user_age = age_row[0]
        age_predicted_max_hr = 220 - user_age

        cutoff = (datetime.now(timezone.utc) - timedelta(days=days)).date().isoformat()

        # --- Method 1: ACSM running-pace + HR method ---
        cur.execute("""
            SELECT id, started_at::date, distance_meters, duration_minutes,
                   avg_hr, sport_type
            FROM activity
            WHERE user_id = %s
              AND started_at::date >= %s
              AND sport_type IN ('running', 'trail_running')
              AND distance_meters IS NOT NULL
              AND duration_minutes IS NOT NULL
              AND avg_hr IS NOT NULL
              AND distance_meters >= 1500
              AND duration_minutes >= 12
        """, (USER_ID, cutoff))
        activities = cur.fetchall()

        acsm_count = 0
        for idx, (act_id, act_date, distance, duration_min, avg_hr, sport) in enumerate(activities):
            # Fetch resting HR for the activity date
            cur.execute("""
                SELECT resting_hr FROM daily_metric
                WHERE user_id = %s AND date = %s
            """, (USER_ID, act_date))
            row = cur.fetchone()
            if not row or not row[0]:
                continue
            resting_hr = row[0]

            if age_predicted_max_hr <= resting_hr:
                continue

            # ACSM running VO2 formula
            speed_m_per_min = distance / duration_min
            vo2_running = 3.5 + 0.2 * speed_m_per_min

            # Heart rate reserve fraction (using age-predicted max HR)
            hrr_fraction = (avg_hr - resting_hr) / (age_predicted_max_hr - resting_hr)
            if hrr_fraction <= 0:
                continue

            vo2max = vo2_running / hrr_fraction

            # Sanity check
            if vo2max < 20 or vo2max > 90:
                continue

            cur.execute("""
                INSERT INTO vo2max_estimate (
                    user_id, date, sport, value, source, activity_id
                ) VALUES (%s, %s, %s, %s, %s, %s)
                ON CONFLICT (user_id, date, sport) DO UPDATE SET
                    value = EXCLUDED.value,
                    source = EXCLUDED.source,
                    activity_id = EXCLUDED.activity_id
            """, (
                USER_ID, act_date, sport,
                round(vo2max, 1), "running_pace_hr", act_id,
            ))
            acsm_count += 1

            # Commit every 50 records to limit memory
            if acsm_count % 50 == 0:
                db.commit()

        # --- Method 2: Uth method from resting HR (batched to limit memory) ---
        cur.execute("""
            SELECT date, resting_hr FROM daily_metric
            WHERE user_id = %s
              AND date >= %s
              AND resting_hr IS NOT NULL
              AND resting_hr > 0
            ORDER BY date DESC
        """, (USER_ID, cutoff))

        uth_count = 0
        while True:
            daily_rows = cur.fetchmany(100)
            if not daily_rows:
                break
            for d_date, resting_hr in daily_rows:
                if resting_hr < 30 or resting_hr > 100:
                    continue

                vo2max_uth = 15.3 * (age_predicted_max_hr / resting_hr)

                if vo2max_uth < 20 or vo2max_uth > 90:
                    continue

                cur.execute("""
                    INSERT INTO vo2max_estimate (
                        user_id, date, sport, value, source
                    ) VALUES (%s, %s, %s, %s, %s)
                    ON CONFLICT (user_id, date, sport) DO UPDATE SET
                        value = EXCLUDED.value,
                        source = EXCLUDED.source
                """, (
                    USER_ID, d_date, "general",
                    round(vo2max_uth, 1), "uth_method",
                ))
                uth_count += 1
            # Commit each batch
            db.commit()

        if acsm_count or uth_count:
            print(f"  VO2max estimates: {acsm_count} ACSM (running), {uth_count} Uth (daily)")
    except Exception as e:
        db.rollback()
        print(f"  Failed to compute VO2max: {e}", file=sys.stderr)
    finally:
        cur.close()


def main():
    has_tokens = (
        os.path.exists(os.path.join(TOKEN_DIR, "oauth1_token.json"))
        and os.path.exists(os.path.join(TOKEN_DIR, "oauth2_token.json"))
    )

    if not has_tokens and (not GARMIN_EMAIL or not GARMIN_PASSWORD):
        print("No Garmin tokens or credentials configured, skipping sync")
        _clear_sync_status()
        return

    print(f"Starting Garmin sync at {datetime.now(timezone.utc).isoformat()}")
    _write_sync_status("starting", "Authenticating with Garmin...")
    client = get_client()
    if client is None:
        print("Failed to authenticate with Garmin, skipping sync", file=sys.stderr)
        _clear_sync_status()
        return

    # First sync: full history from 2019. Subsequent syncs: 7 days only.
    HISTORY_MARKER = os.path.join(TOKEN_DIR, ".initial_sync_done")
    if os.path.exists(HISTORY_MARKER):
        sync_days = 7
    else:
        # Calculate days from 2019-01-01 to today
        epoch = datetime(2019, 1, 1, tzinfo=timezone.utc).date()
        today = datetime.now(timezone.utc).date()
        sync_days = (today - epoch).days
        print(f"First sync — pulling {sync_days} days of history (from 2019-01-01)...")

    db = get_db()

    today = datetime.now(timezone.utc).date()
    for days_ago in range(sync_days):
        date_str = (today - timedelta(days=days_ago)).isoformat()
        _write_sync_status("daily_stats", f"Syncing {date_str}",
                           int((days_ago / sync_days) * 50))
        sync_daily_stats(client, db, date_str)

    # Garmin API: get_activities(start, limit) — fetch in batches of 100
    _write_sync_status("activities", "Syncing activities...", 50)
    sync_activities(client, db, days=sync_days)

    # Backfill computed fields from raw Garmin JSON
    _write_sync_status("backfill", "Computing zones & strain...", 80)
    backfill_from_raw_json(db)

    _write_sync_status("vo2max", "Computing VO2max estimates...", 90)
    sync_vo2max(client, db, days=sync_days)

    db.close()

    # Mark initial sync complete
    if not os.path.exists(HISTORY_MARKER):
        with open(HISTORY_MARKER, "w") as f:
            f.write(datetime.now(timezone.utc).isoformat())

    _clear_sync_status()
    print("Garmin sync complete")


if __name__ == "__main__":
    main()
